// Generated by tools/build-pages.mjs — do not edit by hand.
// Network first (always fresh when online), cache as offline fallback.
const CACHE = 'linear-lab-11277bd091';
const PRECACHE = ["./",
  "assets/css/lab.css",
  "assets/img/apple-touch-icon.png",
  "assets/img/icon-192.png",
  "assets/img/icon-512.png",
  "assets/img/icon-maskable-512.png",
  "assets/img/icon.svg",
  "assets/js/core/eigen.js",
  "assets/js/core/fields.js",
  "assets/js/core/format.js",
  "assets/js/core/linalg.js",
  "assets/js/core/parse.js",
  "assets/js/core/polyspace.js",
  "assets/js/core/rational.js",
  "assets/js/core/svd.js",
  "assets/js/home.js",
  "assets/js/modules/cob.js",
  "assets/js/modules/common.js",
  "assets/js/modules/comp.js",
  "assets/js/modules/det.js",
  "assets/js/modules/eig.js",
  "assets/js/modules/nl.js",
  "assets/js/modules/nsq.js",
  "assets/js/modules/orth.js",
  "assets/js/modules/poly.js",
  "assets/js/modules/quad.js",
  "assets/js/modules/registry.js",
  "assets/js/modules/span.js",
  "assets/js/modules/svd.js",
  "assets/js/modules/sys.js",
  "assets/js/modules/t2d.js",
  "assets/js/modules/t3d.js",
  "assets/js/ui/controls.js",
  "assets/js/ui/dom.js",
  "assets/js/ui/i18n.js",
  "assets/js/ui/plane2d.js",
  "assets/js/ui/pwa.js",
  "assets/js/ui/scene3d.js",
  "assets/js/ui/shell.js",
  "assets/js/ui/store.js",
  "assets/js/ui/tex.js",
  "assets/js/ui/theme.js",
  "cambio_de_base.html",
  "combinaciones_lineales.html",
  "composiciones.html",
  "determinantes.html",
  "formas_cuadraticas.html",
  "index.html",
  "manifest.webmanifest",
  "matrices_no_cuadradas.html",
  "ortogonalidad.html",
  "polinomios.html",
  "sistemas_lineales.html",
  "svd.html",
  "transformaciones_2D.html",
  "transformaciones_3D.html",
  "transformaciones_no_lineales.html",
  "valores_propios.html",
  "vendor/fonts/ibm-plex-mono-latin-400-normal.woff2",
  "vendor/fonts/ibm-plex-mono-latin-500-normal.woff2",
  "vendor/fonts/ibm-plex-mono-latin-600-normal.woff2",
  "vendor/fonts/ibm-plex-mono-latin-ext-400-normal.woff2",
  "vendor/fonts/ibm-plex-mono-latin-ext-500-normal.woff2",
  "vendor/fonts/ibm-plex-mono-latin-ext-600-normal.woff2",
  "vendor/fonts/manrope-latin-ext-wght-normal.woff2",
  "vendor/fonts/manrope-latin-wght-normal.woff2",
  "vendor/katex/fonts/KaTeX_AMS-Regular.woff2",
  "vendor/katex/fonts/KaTeX_Caligraphic-Bold.woff2",
  "vendor/katex/fonts/KaTeX_Caligraphic-Regular.woff2",
  "vendor/katex/fonts/KaTeX_Fraktur-Bold.woff2",
  "vendor/katex/fonts/KaTeX_Fraktur-Regular.woff2",
  "vendor/katex/fonts/KaTeX_Main-Bold.woff2",
  "vendor/katex/fonts/KaTeX_Main-BoldItalic.woff2",
  "vendor/katex/fonts/KaTeX_Main-Italic.woff2",
  "vendor/katex/fonts/KaTeX_Main-Regular.woff2",
  "vendor/katex/fonts/KaTeX_Math-BoldItalic.woff2",
  "vendor/katex/fonts/KaTeX_Math-Italic.woff2",
  "vendor/katex/fonts/KaTeX_SansSerif-Bold.woff2",
  "vendor/katex/fonts/KaTeX_SansSerif-Italic.woff2",
  "vendor/katex/fonts/KaTeX_SansSerif-Regular.woff2",
  "vendor/katex/fonts/KaTeX_Script-Regular.woff2",
  "vendor/katex/fonts/KaTeX_Size1-Regular.woff2",
  "vendor/katex/fonts/KaTeX_Size2-Regular.woff2",
  "vendor/katex/fonts/KaTeX_Size3-Regular.woff2",
  "vendor/katex/fonts/KaTeX_Size4-Regular.woff2",
  "vendor/katex/fonts/KaTeX_Typewriter-Regular.woff2",
  "vendor/katex/katex.min.css",
  "vendor/katex/katex.min.mjs",
  "vendor/three/three-lab.min.js"];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k.startsWith('linear-lab-') && k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    fetch(req)
      .then((res) => {
        if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((cache) => cache.put(req, copy)); }
        return res;
      })
      .catch(() => caches.match(req, { ignoreSearch: true }).then((hit) => hit || caches.match('./index.html'))),
  );
});
